# This playbook will check that a LUKS encrypted drive you provide with variable 'crypt_device' is present,
# (encrypted drive should already be open, these tasks are being written to replace the encryption key from one set in a kickstart)
# the playbook then adds a new password (not stored somewhere in plain text), and then removes the insecure kickstart's set password.  
---
- hosts: all
        include_vars: luks-vars.yml
  tasks:
     - name: check if LUKS present
       shell: "cryptsetup luksDump {{ crypt_device }}"
     - name: Add new password to luks device
       shell: "printf '%s\n' '{{ current_pass }}' '{{ new_pass }}' '{{ new_pass }}' | cryptsetup --force-password luksAddKey {{ crypt_device}}"
     - name: Remove insecure kickstart password from LUKS encrypted drive
       shell: "echo -n '{{ current_pass }}' |cryptsetup luksRemoveKey /dev/nvme1n1"
~                                                                                             
